### ISSUE TITLE
HostConfig.toBuilder() returns empty object

### ISSUE THREAD

**Issue by ko-mueller** [dmandalidis/docker-client#166]
## Description
I have started to port one of our projects from Spotify's docker-client to your fork. We have the following piece of code:

```java
@Override
protected HostConfig additionalHostConfig(HostConfig config) {
  return config.toBuilder()
          // Add some additional configuration here.
          // Omitted the irrelevant details. 
          .build();
}
```

The idea is that we have a basic HostConfig which sub classes can extend with additional configuration options. This works with Spotify's docker-client but after using your fork toBuilder() returns an empty object instead of a pre-populated builder, i.e. the original configuration is lost. Looks like that this has been introduced when moving from autovalue to immutables.

On a side note, I also can't pass around HostConfig.Builder because this interface is not public.

## How to reproduce
```java
HostConfig.builder()
    .addSysctl("key", "value")
    .build()
    .toBuilder()
    .build()
```

## What do you expect
The code snippet above should return a HostConfig object with one entry for "sysctl".

## What happened instead
The code snippet above returns an empty HostConfig object.

## Software:
- `docker version`: 19.03.8-ce (both client and server)
- docker-client version: 3.2.0

**Comment by dmandalidis** [comment]
Hi @ko-mueller and thanks for the detailed bug report. You 're right about the `toBuilder` method, it appears I missed something (checked that others `toBuilder` methods are not affected as well).

What I don't get is about the visibility of `HostConfig.Builder` since interfaces are public by default, while I checked that I can pass around this in a test client project I use. Could you please clarify?

(Once this is sorted out, I will take a patch release with this issue so that you can move on quickly)

**Comment by dmandalidis** [comment]
(keep it open to finalize the discussion)

**Comment by ko-mueller** [comment]
Thank you for your quick response! Very much appreciated!

Forget my comment about HostConfig.Builder, I probably haven't tested it properly yesterday. I just tried it out again and it works as expected.

**Comment by dmandalidis** [comment]
No problem @ko-mueller, starting a release now for 3.2.1, it should be available within the next hour
